version: "3.8"
   
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: userreact
      MYSQL_PASSWORD: passwordreact
      MYSQL_DATABASE: react
      MYSQL_ROOT: root
      MYSQL_ROOT_PASSWORD: iamroot
    restart:
      unless-stopped
    volumes:
      - ./db_data:/var/lib/mysql
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql:ro
    ports:
      - "3306:3306"
  